name: deps-review
on: [pull_request]
jobs:
  dependency-review:
    name: pr/deps-review
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
